def printHelpInfo():
    print 'Valid commands: \n'
    print '\tls, cd, cd ., cd .., cat, next, mkdir, help\n'
    print 'Navigating through the subs \n'
    print '\t~$ cd [subreddit] \n'
    print 'Navigating into post \n'
    print '\t~$ cd [postNumber] (int)\n'
    print 'Checking the comments on a sub\n'
    print 'Navigate to the appropriate sub then\n'
    print '\t~$ cd comments\n'
    print 'Post submission on a subreddit\n'
    print 'Navigate to the appropriate sub then\n'
    print '\t~$ mkdir -t [title] -u [body of the post]\n'